x-api-common: &api-common
  image: dalvorsn/rinha-backend-2026:latest
  command: ./api_server resources/references.bin resources/normalization.json resources/mcc_risk.json
  
  deploy:
    resources:
      limits:
        cpus: '0.47'
        memory: 150M

services:
  api1:
    <<: *api-common
    container_name: api1

  api2:
    <<: *api-common
    container_name: api2

  lb:
    image: dalvorsn/rinha-backend-2026:latest
    container_name: lb
    command: /bin/sh -c "sleep 1 && ./lb"
    environment:
      - LB_BACKENDS=api1:9999,api2:9999
      - LB_PORT=9999
    ports:
      - "9999:9999"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.06'
          memory: 50M
